public enum EventsEnum
{
    FIRST_FLOOR,
    SECOND_FLOOR,
    THIRD_FLOOR,
    FOURTH_FLOOR,
    FIFTH_FLOOR,
    SIXTH_FLOOR,
    SEVENTH_FLOOR,
    EIGHTH_FLOOR,
    NINTH_FLOOR,
    TENTH_FLOOR,
    ELEVENTH_FLOOR,
    TWELFTH_FLOOR,
    THIRTEENTH_FLOOR
}